name: evergrow_mobile_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_polyline_points: ^1.0.0
  flutter_svg: ^2.0.9
  font_awesome_flutter: ^10.7.0
  geocoder2: ^1.4.0
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  google_fonts: 4.0.4
  google_maps_flutter: ^2.9.0
  http: ^0.13.6
  intl: ^0.19.0
  location: ^6.0.2
  shared_preferences: ^2.0.13
  table_calendar: ^3.1.2
  url_launcher: ^6.3.0
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  flutter_sound: ^9.6.0
  audio_waveforms: ^1.0.5


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/top_crop.png
    - assets/logo.png
    - assets/leaf.png
    - assets/moisture_icon.svg
    - assets/icons/pick.png
    - assets/icons/close.png
    - assets/icons/drought.png
    - assets/icons/frost.png
    - assets/icons/intense_rain.png
    - assets/icons/strong_winds.png
    - assets/icons/drought_recommendation.png
    - assets/icons/frost_recommendation.png
    - assets/icons/rain_recommendation.png
    - assets/icons/wind_recommendation.png

